### PR TITLE
Update home.html

### PR DESCRIPTION
**Pull request by RishiAnand108**
i have updated the stuff in mentioned in issue add it under hackoctober label

### CODE REVIEW

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Hi @RishiAnand108,

Thank you for your work on this PR. However, it appears the update is causing the base page to go blank, making it non-functional. As a result, I won’t be merging this PR. If you’d like, feel free to investigate the issue further and resubmit with adjustments.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
hey @RishiAnand108  to continue from [here](https://discord.com/channels/720788516837261322/1301046353006301285/1301067852949753878), 
this is how it looks 
image

where as the original was:
image

**Comment by SANTHOSH-MAMIDISETTI** [comment]
@RishiAnand108  let me know if you are working on this , else i'll close this pr

**Comment by RishiAnand108** [comment]
sir you can see in code i have done the required changes i dont know why it is showing like thses

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Hi @RishiAnand108, Can you please show me how it looks from your side when you run it? It might help us pinpoint the issue that's causing the blank page.

Additionally, I’d appreciate it if you could provide a step-by-step breakdown of how you ran the code. For instance:
- Which files did you modify?
- Did you run any specific commands in the terminal?
- How did you start the application?

The steps you took will help us troubleshoot more effectively and get to the bottom of this issue.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
closing this issue , due to inactivity.

**Pull request closed without merging**
